# Generated by Django 6.0.1 on 2026-01-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', 'Kakao'), ('google', 'Google')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.URLField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_user_id'], name='api_sociala_provide_6ec298_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
