# Generated by Django 6.0.1 on 2026-01-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='profile_image',
        ),
    ]
