# Generated by Django 6.0.1 on 2026-02-13 13:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reviewcomment_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='reviews/', validators=[api.validators.validate_image_file_size]),
        ),
    ]
