# Generated by Django 6.0.1 on 2026-02-13 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bingoboard',
            index=models.Index(fields=['user', '-created_at'], name='api_bingobo_user_id_8605b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bingoboard',
            index=models.Index(fields=['is_completed', 'completed_at'], name='api_bingobo_is_comp_ca0016_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_public', '-created_at'], name='api_review_is_publ_38eb6f_idx'),
        ),
    ]
